eatsat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<restaurant_name>[,\w\d\s_&]+)/(?P<restaurant_address>[,\w\d\s_]+)/$', views.restaurant, name='restaurant'),
    url(r'^(?P<restaurant_name>[,\w\d\s_&]+)/(?P<restaurant_address>[,\w\d\s_]+)/update_wait_time/$', views.update_wait_time, name='update_wait_time'),
    url(r'^(?P<restaurant_name>[,\w\d\s_&]+)/(?P<restaurant_address>[,\w\d\s_]+)/new_eatsat/$', views.new_eatsat, name='new_eatsat'),
    url(r'^(?P<restaurant_name>[,\w\d\s_&]+)/(?P<restaurant_address>[,\w\d\s_]+)/cancel_eatsat/(?P<account_id>[\d]+)/$', views.cancel_eatsat, name='cancel_eatsat'),

    
]

reservation/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
               
    url(r'^admin/', include(admin.site.urls)),
    url(r'^eatsat/', include('eatsat.urls', namespace="eatsat")),
    

]

eatsat/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey

# Create your models here.
class Restaurant(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    estimated_wait_time = models.IntegerField()
    def __str__(self):
        return self.name
class Account(models.Model):
    account_id = models.PositiveIntegerField()
    last_name = models.CharField(max_length=200)
    payment_info = models.CharField(max_length=200)
    def __str__(self):
        return str(self.account_id)

class Eatsat(models.Model):
    account = ForeignKey(Account)
    restaurant = ForeignKey(Restaurant)
    party_size = models.PositiveIntegerField()
    wait_time = models.PositiveIntegerField(null=True, blank=True)
    meal_time = models.DateTimeField(null=True, blank=True
)
    def __str__(self):
        return str(self.account.account_id) + " " + self.restaurant.name

eatsat/views.py
from eatsat.models import Restaurant, Account, Eatsat
from django.shortcuts import render
from django.http.response import HttpResponseRedirect

from django.core.urlresolvers import reverse
import datetime

def index(request):
    restaurant_List = Restaurant.objects.order_by('name')
    context = {'restaurant_List': restaurant_List}
    return render(request, 'index.html', context)

def restaurant(request, restaurant_name, restaurant_address):
    restaurant = Restaurant.objects.get(name=restaurant_name, address=restaurant_address)
    accounts_at_restaurant = Eatsat.objects.filter(restaurant__name=restaurant_name, restaurant__address=restaurant_address).values('account')
    eatsat_list = Eatsat.objects.filter(restaurant__name=restaurant_name, restaurant__address=restaurant_address);
    accounts = Account.objects.exclude(id__in=accounts_at_restaurant)
    context = {'restaurant': restaurant, 'accounts':accounts, 'eatsat_list':eatsat_list}
    return render(request, 'restaurant.html', context)

def update_wait_time(request, restaurant_name, restaurant_address):
    restaurant = Restaurant.objects.get(name=restaurant_name, address=restaurant_address)
    restaurant.estimated_wait_time = request.POST['new_wait_time']
    restaurant.save()
    return HttpResponseRedirect(reverse('eatsat:restaurant', args=(restaurant_name,restaurant_address)))

def new_eatsat(request, restaurant_name, restaurant_address):
    eatsat_party_size = request.POST['party_size']
    account_id = request.POST['account_id']
    eatsat_restaurant = Restaurant.objects.get(name=restaurant_name, address=restaurant_address)
    eatsat_account = Account.objects.get(account_id=account_id)
    eatsat_wait_time = None
    eatsat_meal_time = None
    if (request.POST['eatsat_type'] == "walkin"):
        eatsat_wait_time = eatsat_restaurant.estimated_wait_time     
    else:
        eatsat_meal_time_string = request.POST['reservation_time']
        eatsat_meal_time = datetime.datetime.strptime(eatsat_meal_time_string,
                                                     '%Y-%m-%dT%H:%M')
    new_eatsat = Eatsat(party_size=eatsat_party_size, account=eatsat_account, restaurant=eatsat_restaurant, wait_time=eatsat_wait_time, meal_time=eatsat_meal_time)
    new_eatsat.save()
    return HttpResponseRedirect(reverse('eatsat:restaurant', args=(restaurant_name, restaurant_address,)))

def cancel_eatsat(request, restaurant_name, restaurant_address, account_id):
    eatsat = Eatsat.objects.get(restaurant__name=restaurant_name, restaurant__address=restaurant_address, account__account_id=int(account_id))
    eatsat.delete()
    return HttpResponseRedirect(reverse('eatsat:restaurant', args=(restaurant_name, restaurant_address,)))

eatsat/templates/base_site.html
<!DOCTYPE html>
<html lang="en">
	{% block head %}
	<head>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		
		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
		
		<title>{% block title %}{% endblock %} </title>
	</head>
	{% endblock %}
	<body>
		<div id="content">
			{% block content %}{% endblock %}
		</div>
	</body>
</html>

eatsat/templates/index.html
{% extends "base_site.html" %}
{% block title %} Restaurants {% endblock %}
{% block content %}
{% if restaurant_List %}
<h1>Select a restauraunt</h1>
<ul>
	{% for restaurant in restaurant_List %}
	<li>
		<a href="{% url 'eatsat:restaurant' restaurant.name restaurant.address %}"> {{restaurant.name}}</a>
	</li>
	{% endfor %}
</ul>
{% else %}
<p>
	No restaurants available
</p>
{% endif %}
{% endblock %}

eatsat/templates/restaurant.html
{% extends "base_site.html" %}
{% block title %} {{restaurant.name}} {% endblock %}
{% block content %}
<h1>{{restaurant.name}}</h1>
<h2>{{restaurant.address}}</h2>
<form action = "{% url 'eatsat:update_wait_time' restaurant.name restaurant.address %}" method = "post">
	{% csrf_token %}
	Current estimated wait time is {{restaurant.estimated_wait_time}} minutes
	<br>
	<input type= "number" name = "new_wait_time" id="new_wait_time">
	<input type= "submit" value = "Update estimated wait time">
</form>
<br>
<form action = "{% url 'eatsat:new_eatsat' restaurant.name restaurant.address %}" method = "post">
	{% csrf_token %}
	Account:
	<br>
	<select name = "account_id">
		{% for account in accounts %}
		<option value = "{{account.account_id}}"> {{account.last_name}} </option>
		{% endfor %}
	</select>
	<br>
	Enter party size:
	<br>
	<input type = 'number' name = "party_size">
	<br>
	<script type="text/javascript" charset="utf-8">
		function hide_reservation() {
			document.getElementById('reservation_time_div').setAttribute('hidden', true);
			document.getElementById('reservation_time').removeAttribute('required');
			return false;
		}

		function show_reservation() {
			document.getElementById('reservation_time_div').removeAttribute('hidden');
			document.getElementById('reservation_time').setAttribute('required', true);
			return false;
		}
	</script>
	<input type = "radio" value = "walkin" name = "eatsat_type" checked onclick = "hide_reservation()">
	Walk In
	<input type = "radio" value = "reservation" name = "eatsat_type" onclick = "show_reservation()">
	Reservation
	<div id = "reservation_time_div" hidden>
		<input type = "datetime-local" name = "reservation_time" id = "reservation_time">
	</div>
	<br>
	<input type = "submit" value = "Add scheduled meal">
</form>
{% if eatsat_list %}
<h2>Scheduled Meals</h2>
<ul>
	{% for eatsat in eatsat_list %}
	<li>
		{{eatsat.account.last_name}}, party of {{eatsat.party_size}}
		(<a href = "{% url 'eatsat:cancel_eatsat' restaurant.name restaurant.address eatsat.account.account_id %}">cancel</a>)
	</li>
	{% endfor %}
</ul>
{% else %}
<p>
	No meals currently scheduled
</p>
{% endif %}
{% endblock %}